"""Synthetic-only futures research mechanics with no I/O or fitting."""

from .abstention import FuturesInferenceUnit, InferenceEligibility, assess_inference_unit
from .bootstrap import (
    apply_shared_indices,
    stationary_bootstrap_index_kernel,
    stationary_bootstrap_index_rows,
    stationary_bootstrap_indices,
)
from .contracts import (
    ResearchContractError,
    SyntheticOnlyPermit,
    assert_disjoint_partitions,
    make_synthetic_permit,
    require_synthetic_permit,
)
from .controls import (
    NegativeControlOutcome,
    NegativeControlResult,
    NegativeControlState,
    apply_negative_control_indices,
    circular_block_derangement_indices,
    evaluate_negative_controls,
    synthetic_noise_control,
)
from .cscv import CSCVResult, exhaustive_cscv_pbo
from .dsr import DeflatedSharpeResult, deflated_sharpe_ratio
from .economics import (
    Direction,
    EconomicsBinding,
    FuturesPnLRow,
    FuturesReturnBasis,
    build_pnl_row,
    pnl_rows_to_float64,
)
from .hac import HACMeanResult, hac_t_statistic, newey_west_mean
from .interval_identity import (
    DecisionTimeIdentityCharter,
    IntervalIdentityDecision,
    IntervalIdentitySegment,
    IntervalResolutionStatus,
    IntervalRole,
    RoleIntervalWindow,
    VerifiedIntervalIdentity,
    VerifiedRoleIntervalIdentity,
    assess_interval_identity_bundle,
    coverage_denominator_indices,
)
from .multiple_testing import (
    RomanoWolfResult,
    romano_wolf_from_differentials,
    romano_wolf_stepdown,
)
from .power import PowerPlan, training_only_mde
from .sleeves import (
    ResearchBookCharter,
    ResearchBookState,
    SleeveGateResult,
    SleeveKey,
    SleeveState,
    SleeveThresholds,
    SyntheticSleeveMetrics,
    evaluate_research_book,
    evaluate_synthetic_sleeve,
)
from .splits import (
    InnerFold,
    NestedFold,
    SessionWindow,
    TemporalSamples,
    nested_chronological_splits,
    purge_and_post_embargo_indices,
)

__all__ = [
    "CSCVResult",
    "DeflatedSharpeResult",
    "DecisionTimeIdentityCharter",
    "Direction",
    "EconomicsBinding",
    "FuturesInferenceUnit",
    "FuturesPnLRow",
    "FuturesReturnBasis",
    "HACMeanResult",
    "InferenceEligibility",
    "IntervalIdentityDecision",
    "IntervalIdentitySegment",
    "IntervalResolutionStatus",
    "IntervalRole",
    "InnerFold",
    "NegativeControlOutcome",
    "NegativeControlResult",
    "NegativeControlState",
    "NestedFold",
    "PowerPlan",
    "ResearchBookCharter",
    "ResearchBookState",
    "ResearchContractError",
    "RomanoWolfResult",
    "RoleIntervalWindow",
    "SessionWindow",
    "SleeveGateResult",
    "SleeveKey",
    "SleeveState",
    "SleeveThresholds",
    "SyntheticOnlyPermit",
    "SyntheticSleeveMetrics",
    "TemporalSamples",
    "VerifiedIntervalIdentity",
    "VerifiedRoleIntervalIdentity",
    "apply_negative_control_indices",
    "apply_shared_indices",
    "assert_disjoint_partitions",
    "assess_inference_unit",
    "assess_interval_identity_bundle",
    "build_pnl_row",
    "circular_block_derangement_indices",
    "coverage_denominator_indices",
    "deflated_sharpe_ratio",
    "evaluate_negative_controls",
    "evaluate_research_book",
    "evaluate_synthetic_sleeve",
    "exhaustive_cscv_pbo",
    "hac_t_statistic",
    "make_synthetic_permit",
    "nested_chronological_splits",
    "newey_west_mean",
    "pnl_rows_to_float64",
    "purge_and_post_embargo_indices",
    "require_synthetic_permit",
    "romano_wolf_from_differentials",
    "romano_wolf_stepdown",
    "stationary_bootstrap_index_kernel",
    "stationary_bootstrap_index_rows",
    "stationary_bootstrap_indices",
    "synthetic_noise_control",
    "training_only_mde",
]
